MARGIN = 1
DIRECTIONS = 8

N_SPHEROS = 20

NODES_WIDTH = 10
NODES_HEIGHT = 10
NODES_DISTANCE = 50

WIDTH = NODES_WIDTH * NODES_DISTANCE
HEIGHT = NODES_HEIGHT * NODES_DISTANCE

VELOCITY = NODES_DISTANCE / 10